### ISSUE TITLE
Few Fixes? Details and Cookies within.

### ISSUE THREAD

**Issue by TagCraftMC** [Maxetto/AntiJoinBot#3]
The following fixes should allow user bypass to work correctly.

Line: 
283: this.db.userBlacklist.containsKey(e.getPlayer())) TO this.db.userBlacklist.containsKey(e.getPlayer().getName()))

284: this.db.userBlacklist.get(e.getPlayer()) TO this.db.userBlacklist.get(e.getPlayer().getName())

285: ((Boolean)this.db.userBlacklist.get(e.getPlayer())).booleanValue() TO ((Boolean)this.db.userBlacklist.get(e.getPlayer().getName())).booleanValue()

The reload command wasn't working correctly either (not reading new data placed in (example changing a users block status from false to true)

After line 388 you might want to add loadDBOfflinetoRAM(); to load the changes (as well as loadDBtoRAM for non offline mode).
Wouldn't hurt to clear the HashMaps prior to the loads in each of them as well I guess.

I hoped this kinda helped.

**Comment by Maxetto** [comment]
I know reload command is just reloading DB informations ATM.
It will be fixed with new version.

Thank you for your help! :wink:
