### ISSUE TITLE
Adding to blacklist?

### ISSUE THREAD

**Issue by GershonR** [Maxetto/AntiJoinBot#6]
I have a bunch still coming through I think the default 2 blacklists blocks around 50% of them, I found a bunch of blacklists online but i'm not sure how to add them to the config:
http://i.imgur.com/0UMpYz9.png

http://pastebin.com/bXWsxizw

It seems like these work well:
http://www.sorbs.net/lookup.shtml
http://www.barracudacentral.org/lookups/lookup-reputation

but i'm not sure how to get a URL from those that returns something

**Comment by Maxetto** [comment]
Those blacklist are not APIs, meaning that you can't add them to the plugin.
More specifically they are DNSBL with their own protocol to implement.

Also, they seem to blacklist my current IP from a violation in 2008.

P.S. You have some really old values in the Config. I suggest you to let it regen ;)

**Comment by GershonR** [comment]
Is there any other blacklists I can use? I just need to stop around 30% more of them and I can ip-ban the rest

**Comment by Maxetto** [comment]
Just let the database grow by time and it will block 90%+ of attacks.

There's one blacklist I'm going to add but it's not a simple boolean, so you can't just add it right now and it's too much limited (500 request per day).

There are no any other good free blacklist AFAIK

**Comment by GershonR** [comment]
The more times he tries to attack, the more it will automatically detect its spam and add it?

**Comment by Maxetto** [comment]
Yeah, but only day by day. Just let the blacklist update themselves.

**Comment by GershonR** [comment]
Alright awesome man thanks alot!
